stages:
  - dist
  - test
  - catch

#
# dist - Проверка оформления дистрибутива (авторские тесты)
#

dist:
  stage: dist
  except:
    - tags
  tags:
    - docker
    - runner1
  image: docker.220v.ru/220v/node:4
  script:
    - yarn run lint

#
# test - Модульные тесты
#

test:
  stage: test
  tags:
    - docker
  image: docker.220v.ru/220v/node:4
  script:
    - yarn install
    - unbuffer yarn run test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'


#
# catch - Реакция на провал пайплайна
#

catch:on-failure:
  stage: catch
  except:
    - tags
  tags:
    - shell
    - runner1
  when: on_failure
  script:
    # Этот скрипт установлен в систему, а его исходник находится в репозитории 220V/ci
    - ccxx-youtrack-reject $CI_PROJECT_NAME $CI_PIPELINE_ID $GITLAB_AUTOBOT_TOKEN $YOUTRACK_AUTOBOT_TOKEN
